### ISSUE TITLE
Application breaks when I type "+\s+"

### ISSUE THREAD

**Issue by arantespp** [CGReinhold/regex-game#1]
### Description

Application breaks when I type `+\s+`, at any level.

![image](https://user-images.githubusercontent.com/16626980/115908469-95061c80-a440-11eb-80fc-6b8b0d81ca1a.png)

**Comment by CGReinhold** [comment]
Quick fix (probably not the best) on this commit 86248a13507b2f1d1d6d665388591573d09d6431
