### ISSUE TITLE
Please add the hosted website

### ISSUE THREAD

**Issue by monsterbrain** [CGReinhold/regex-game#2]
https://regex-mistery.cgreinhold.dev/

Please add this to the github website link so that anyone can try it out.

**Comment by CGReinhold** [comment]
Thank you for the suggestion @monsterbrain! I just added it on [db01654](https://github.com/CGReinhold/regex-game/commit/db01654e44ceab9ed2b0c81aa0a84f826fac8378).

**Comment by monsterbrain** [comment]
Adding here also would be nice

![image](https://user-images.githubusercontent.com/10105094/221525560-aa127cad-3791-4beb-a49d-38dde157fe26.png)

**Comment by CGReinhold** [comment]
Nice catch! I added it there as well. Thanks!
